import Header from "./components/Header";
import "../app/globals.css";

export const metadata = {
  title: "CIAR",
  description: "Generated by Jianny",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen w-full overflow-hidden flex justify-center bg-slate-200 poppins-light">
          <div className="max-w-4xl w-full relative">
              <Header />
              {children}
          </div>
      </body>
    </html>
  );
}
