import Header from "../components/Header";
import "../app/globals.css";

export const metadata = {
  title: "CIAR",
  description: "Generated by Jianny",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen w-full overflow-hidden flex justify-center bg-slate-200 poppins-light p-2 text-sm md:text-md">
        <div className="max-w-4xl h-full w-full flex flex-col relative">
          <Header />
          
          <div className="flex-grow overflow-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
